spring:
   application:
      name: api-gateway
   cloud:
      gateway:
        enabled: true
        httpclient:
          ssl:
            useInsecureTrustManager: true

        routes:
         - id: httpbin-api
           uri: https://httpbin.org
           predicates:
            - Path=/api/**
           filters:
            - StripPrefix=1

server:
   port: 8080
   ssl:
     enabled: true
#     key-alias: scg
#     key-store-password: scg1234
#     key-store: classpath:scg-keystore.p12
#     key-store-type: PKCS12

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'