version: "3.9"
services:
  web-lb:
    image: nginx
    depends_on:
      - web-storefront
      - mock-service
    ports:
      - 9443:443
    environment:
      - WEB_FRONTEND_URL=${WEB_FRONTEND_URL:-http://web-storefront:80}
      - API_GATEWAY_URL=${API_GATEWAY_URL:-http://mock-service:1080}
      - NGINX_FORWARDED_HOST=localhost
      - NGINX_SSL_CERT=localhost+2.pem
      - NGINX_SSL_CERT_KEY=localhost+2-key.pem
    volumes:
      - ./web-lb/templates:/etc/nginx/templates
      - ./web-lb/certs:/etc/nginx/ssl
  web-storefront:
    image: nginx
    ports:
      - 8082:80
    environment:
      - WEB_APP_VERSION=${WEB_APP_VERSION:-0.0.1}
    volumes:
      - type: bind
        source: ./web-storefront/storefront/build
        target: /usr/share/nginx/html
      - ./web-storefront/templates:/etc/nginx/templates
  api-gateway:
    image: ghcr.io/soleo/api-gateway:main
    ports:
      - 8081:8080
      - 8931:8930
    volumes:
      - type: bind
        source: ./api-gateway
        target: /etc/app
  mock-service:
    image: mockserver/mockserver:latest
    depends_on:
      - api-gateway
    ports:
      - 1080:1080
      - 1090:1090
    environment:
      MOCKSERVER_LOG_LEVEL: DEBUG
      SERVER_PORT: 1080
      PROXY_REMOTE_HOST: api-gateway
      PROXY_REMOTE_PORT: 8080
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - type: bind
        source: ./mock-service
        target: /config